- name: Install Keepalived packages
  dnf:
     name: keepalived
     state: present
     update_cache: True

- name: Copy config files
  vars:
    ka_state: MASTER
    vrouter_id: 51
    ka_priority: 101
    ka_vip: 10.0.2.100/24
  template: 
     src: templates/keepalived.conf.j2
     dest: /etc/keepalived/keepalived.conf
     mode: '0640'
     owner: root
  when: "'master' in inventory_hostname"

- name: Copy config files
  vars:
    ka_state: SLAVE
    vrouter_id: 51
    ka_priority: 100
    ka_vip: 10.0.2.100/24
  template:
     src: templates/keepalived.conf.j2
     dest: /etc/keepalived/keepalived.conf
     mode: '0640'
     owner: root
  when: "'slave' in inventory_hostname" 

- name: Enable and restart Keepalived service 
  service:
   name: keepalived
   enabled: yes
   state: restarted
